baseURL = "http://botahamec.github.io/"
theme = "hugo-coder"
title = "Botahamec"
languageCode = "en-us"
defaultcontentlanguage = "en"
publishDir = ".."

[params]
author = "Mike White"
info = "Hobbyist Computer Science Student"
description = "JMike White's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/bota1.jpg"

dateformat = "January 2, 2006"

# favicon_32 = "/img/favicon-32x32.png"
# favicon_16 = "/img/favicon-16x16.png"

footercontent = ""

hidecredits = false
hidecopyright = false
hidefooter = false

colorscheme = "dark"

rtl = false

math = true

[[params.social]]
name = "YouTube"
icon = "fab fa-youtube fa-2x"
weight = 1
url = "https://www.youtube.com/channel/UCgmy0-lP0GHHI_Mh62ALJvA"
[[params.social]]
name = "Github"
icon = "fab fa-github fa-2x"
weight = 2
url = "https://github.com/botahamec/"
[[params.social]]
name = "StackOverflow"
icon = "fab fa-stack-overflow fa-2x"
weight = 3
url = "https://stackoverflow.com/users/12195838/botahamec"

[[main.menu]]
name = "Projects"
weight = 1
url = "/projects/"
[[main.menu]]
name = "Blog"
weight = 2
url = "/posts/"